version: "3"

services:
  mysqlsrv:
    image: mysql
    environment: 
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "golang"
    ports: 
      - 3306:3306
    volumes: 
      - /home/thiago/database/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network
  
  adminer:
    image: adminer
    ports:
      - 8082:8080
    networks:
      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge